import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Radom fox</title>
        <meta name="description" content="Generated by Radom fox" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 className="text-3xl font-bold underline">Republica Dominicana Campeón</h1>
      </main>
    </>
  )
}
