import { useState } from "react";
import { RandomFox } from "@/components/RandomFox";
import Head from "next/head";

const randomNumber = () => Math.floor(Math.random() * 122) + 1;

export default function Home() {
  const [images, setImages] = useState<string[]>([
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
  ]);
  return (
    <>
      <Head>
        <title>Radom fox</title>
        <meta name="description" content="Generated by Radom fox" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Republica Dominicana Campeón
        </h1>
        {images.map((img, index) => (
          <div className="p-4" key={index}>
            <RandomFox image={img} />
          </div>
        ))}
      </main>
    </>
  );
}
